Loading mpi OPENMPI version 4.1.1
Traceback (most recent call last):
  File "/opt/pub/spack/python/3.8.11/intel/2021.3.0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/pub/spack/python/3.8.11/intel/2021.3.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/lovelace/proj/proj813/sabrina/py38/lib/python3.8/site-packages/mpi4py/futures/__main__.py", line 74, in <module>
    main()
  File "/home/lovelace/proj/proj813/sabrina/py38/lib/python3.8/site-packages/mpi4py/futures/__main__.py", line 62, in main
    run_command_line()
  File "/home/lovelace/proj/proj813/sabrina/py38/lib/python3.8/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/opt/pub/spack/python/3.8.11/intel/2021.3.0/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/pub/spack/python/3.8.11/intel/2021.3.0/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/pub/spack/python/3.8.11/intel/2021.3.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "main.py", line 13, in <module>
    running_all_instance_choose_capacity(
TypeError: running_all_instance_choose_capacity() takes 1 positional argument but 2 were given
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
